#!/usr/bin/zsh
typeset -a Services
typeset CONF='~/check-services.cf'
if [[ -r ${~CONF} ]] { #{{{
    Services=$(grep -v '\#' ${~CONF})
} else {
    print "Can't read ${CONF}"
} #}}}
for S (${(f)Services}) { #{{{
    TEST=$(sudo service ${S} status)
    if [[ "${TEST}" =~ 'running' ]] {
        print "Service ${S} OK."
    } else {
    print "Service ${S} not OK. (${TEST})"
    }
} #}}}
